# Generated by Django 4.2 on 2023-04-08 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talaba_s', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Yonalishlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yonalish', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Yonalishlar',
            },
        ),
        migrations.AlterField(
            model_name='fakultet',
            name='fakultet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('manzil', models.CharField(max_length=150)),
                ('kurs', models.CharField(choices=[('1', 'birinchi kurs'), ('2', 'ikkinchi kurs'), ('3', 'uchinchi kurs'), ('4', "to'rtinchi kurs")], max_length=2)),
                ('guruh_n', models.CharField(max_length=15)),
                ('pasp_s', models.CharField(max_length=2)),
                ('pasp_n', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba_s.fakultet')),
            ],
            options={
                'verbose_name_plural': 'Talabalar',
            },
        ),
        migrations.CreateModel(
            name='Oqituvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba_s.fakultet')),
            ],
            options={
                'verbose_name_plural': 'Oqituvchilar',
            },
        ),
        migrations.CreateModel(
            name='Baholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestr', models.BinaryField()),
                ('ball', models.BinaryField()),
                ('sana_kir', models.DateTimeField(auto_now_add=True)),
                ('sana_updated', models.DateTimeField(auto_now=True)),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba_s.fakultet')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba_s.fanlar')),
                ('oqituvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba_s.oqituvchilar')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba_s.talaba')),
                ('yonalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba_s.yonalishlar')),
            ],
            options={
                'verbose_name_plural': 'Baholar',
            },
        ),
    ]
