# Generated by Django 4.2 on 2023-04-09 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talaba_s', '0002_fanlar_yonalishlar_alter_fakultet_fakultet_talaba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talaba',
            name='daraja',
            field=models.CharField(choices=[('bakalavr', 'Bakalavr'), ('magistr', 'Magistr')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='baholar',
            name='fakultet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba_s.fakultet', verbose_name='Fakultet'),
        ),
        migrations.AlterField(
            model_name='baholar',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba_s.fanlar', verbose_name='Fan nomi'),
        ),
        migrations.AlterField(
            model_name='baholar',
            name='oqituvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba_s.oqituvchilar', verbose_name="O'qituvchi"),
        ),
        migrations.AlterField(
            model_name='baholar',
            name='semestr',
            field=models.BinaryField(verbose_name='Semestr'),
        ),
        migrations.AlterField(
            model_name='baholar',
            name='talaba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba_s.talaba', verbose_name='Talaba'),
        ),
        migrations.AlterField(
            model_name='baholar',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba_s.yonalishlar', verbose_name="Yo'nalish"),
        ),
        migrations.AlterField(
            model_name='fakultet',
            name='fakultet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fakultet'),
        ),
        migrations.AlterField(
            model_name='fanlar',
            name='fan',
            field=models.CharField(max_length=50, null=True, verbose_name='Fan nomi'),
        ),
        migrations.AlterField(
            model_name='oqituvchilar',
            name='fakultet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba_s.fakultet', verbose_name='Fakultet'),
        ),
        migrations.AlterField(
            model_name='oqituvchilar',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='oqituvchilar',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='fakultet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba_s.fakultet', verbose_name='Fakultet'),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='guruh_n',
            field=models.CharField(max_length=15, verbose_name='Guruh nomeri'),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='kurs',
            field=models.CharField(choices=[('1', 'birinchi kurs'), ('2', 'ikkinchi kurs'), ('3', 'uchinchi kurs'), ('4', "to'rtinchi kurs")], max_length=2, verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='manzil',
            field=models.CharField(max_length=150, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='pasp_n',
            field=models.CharField(max_length=7, verbose_name='Pasport raqami'),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='pasp_s',
            field=models.CharField(max_length=2, verbose_name='Pasport seriyasi'),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Qayta tahrirlangan vaqti'),
        ),
        migrations.AlterField(
            model_name='yonalishlar',
            name='yonalish',
            field=models.CharField(max_length=100, verbose_name="yo'nalish"),
        ),
    ]
