# Generated by Django 4.2 on 2023-04-15 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talaba_s', '0003_talaba_daraja_alter_baholar_fakultet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baholar',
            name='ball',
        ),
        migrations.RemoveField(
            model_name='baholar',
            name='semestr',
        ),
    ]
